## NUMPY


In [118]:
import numpy as np 
np.__version__

'2.3.0'

In [ ]:
lst = [1,2,3,4,5]
ar1 = np.array(lst, ndmin=3) #ndmin used to specify the dimension of the array
## ar1 = np.array([1,2,"3",4,5]) // output   array(['1', '2', '3', '4', '5'], dtype='<U21')  
ar1
#print(type(ar1))

array([[[1, 2, 3, 4, 5]]])

In [120]:
ar2 = np.arange(1,10)
ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [122]:
arr4 = np.zeros(23)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [123]:
arr5 = np.zeros((2,3))   ## the output has 2 square brackkets therefore 2d array
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [124]:
arr6 = np.linspace(1,10,5)
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [125]:
arr7 = np.arange(1,31).reshape(5,6)
arr7

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [126]:
arr8 = np.random.randint(1,100,10)
arr8

arr9 = np.random.random(10)
arr9

array([0.75609589, 0.30180233, 0.92366047, 0.66327193, 0.72521197,
       0.20705431, 0.98797283, 0.01772015, 0.99855963, 0.29643883])

In [127]:
arr10 = np.arange(60).reshape(6,10)
print(arr10.shape)
print(arr10.dtype)
print(arr10.size)
print(arr10.ndim)

(6, 10)
int64
60
2


In [128]:
print(arr10.ravel())
print(arr10.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [129]:
arr11 = np.arange(60).reshape(6,10)
print(arr11)

arr12 = arr11.T
arr12

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55],
       [ 6, 16, 26, 36, 46, 56],
       [ 7, 17, 27, 37, 47, 57],
       [ 8, 18, 28, 38, 48, 58],
       [ 9, 19, 29, 39, 49, 59]])

In [130]:
arr11 = np.arange(60).reshape(6,10)
print(arr11.shape)

arr12 = arr11.T.shape
arr12

(6, 10)


(10, 6)

In [131]:
## indexing and slicing
## 1-D array (similar concept to list)

ar2 = np.arange(1,10)
print(ar2)

#indexing
print(lst[3])
print(lst[-2])

#slicing
print(ar2[1:4])
print(ar2[:-3])

[1 2 3 4 5 6 7 8 9]
4
4
[2 3 4]
[1 2 3 4 5 6]


In [132]:
## indexing and slicing
## 2-D array  --  [row start : row end : row skip , col start : col end : col skip]

arr11 = np.arange(60).reshape(10,6)
print(arr11[3:4])
print(arr11[3:6, 2:])
print(arr11[3:4, 2:3]) ## since the output is in array we want in int so we do
print(arr11[3:4, 2:3][0][0])


[[18 19 20 21 22 23]]
[[20 21 22 23]
 [26 27 28 29]
 [32 33 34 35]]
[[20]]
20


In [133]:
arr = np.arange(12).reshape(4, 3)
print(arr)
r = arr[::-1, ::-1]  #rows reversed, columns reversed
print(r)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[11 10  9]
 [ 8  7  6]
 [ 5  4  3]
 [ 2  1  0]]


## 3-D array 

In [134]:
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [135]:
arr13 = np.arange(24).reshape(2, 3, 4)
print(arr13)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [136]:
arr = np.zeros((2, 3, 4))
print( arr)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [137]:
arr = np.ones((2, 3, 4))
print(arr)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [138]:
arr = np.random.randint(1, 100, size=(2,3,4))
print(arr)

[[[84 42 89 77]
  [82  7  8 51]
  [77 59 78 12]]

 [[33 19 91 17]
  [55 83 76 32]
  [89 39 26 80]]]


In [139]:
arr = np.linspace(1, 24, 24).reshape(2, 3, 4)
print(arr)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


In [140]:
##slicing in 3d array
##syntax
#[table start: table end: table skip, row start: row end: row skip, col start: col end: col skip]

In [142]:
arr10[0:,1:4,2:4]

array([[[  7,   8],
        [ 12,  13],
        [ 17,  18]],

       [[ 82,  83],
        [ 87,  88],
        [ 92,  93]],

       [[157, 158],
        [162, 163],
        [167, 168]]])

In [146]:
arr10 = np.arange(60).reshape(6,10)
arr10

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [147]:
print(np.max(arr10))
print(np.min(arr10))
print(np.sum(arr10))
print(np.mean(arr10))
print(np.half(arr10))

59
0
1770
29.5
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]]


In [152]:
print(arr10.sort())


None


In [ ]:
arr11 = np.array([2,5,1,9])
arr12 = np.array([2,5,1,9])
arr11.argsort()
#2 5 1 9
#0 1 2 3

array([2, 0, 1, 3])

In [154]:
arr11+2

array([ 4,  7,  3, 11])

In [155]:
arr11*2

array([ 4, 10,  2, 18])